version: '3.2'
services:
  nodejs:
      build: ./nodejs
      ports:
        - "8000:8000"
      volumes:
        - ../frontend:/app
      environment:
        HOST: 0.0.0.0
        PORT: 8000
      restart: always
      command: /usr/local/bin/start.sh